# Generated by Django 2.2.6 on 2019-12-19 11:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=100, unique=True)),
                ('Answer', models.CharField(max_length=500, unique=True)),
                ('position', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(15)])),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('Description', models.CharField(max_length=350, unique=True)),
                ('Image_Link', models.CharField(max_length=300)),
                ('Difficulty', models.IntegerField(validators=[django.core.validators.MaxValueValidator(4)])),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial_Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Position', models.IntegerField(null=True, unique=True)),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Description', models.CharField(max_length=800, null=True, unique=True)),
                ('Image_Link', models.CharField(max_length=300, null=True)),
                ('Tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Help_Centre.Tutorial')),
            ],
        ),
    ]
