# Generated by Django 2.2.6 on 2019-12-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Help_Centre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='Image_Link_High_Res',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tutorial_step',
            name='Image_Link_High_Res',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='Image_Link',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tutorial_step',
            name='Description',
            field=models.CharField(max_length=800, unique=True),
        ),
        migrations.AlterField(
            model_name='tutorial_step',
            name='Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tutorial_step',
            name='Position',
            field=models.IntegerField(unique=True),
        ),
    ]
