# Generated by Django 2.2.6 on 2019-12-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Help_Centre', '0002_auto_20191219_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial_step',
            name='Description',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='tutorial_step',
            name='Position',
            field=models.IntegerField(),
        ),
    ]
